### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by KisAaki** [zhuoxiao-chen/ReDB-DA-3Ddet#3]
When I'm downloading the dataset:KITTI using the command:
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml
I got a error called:segmentation fault(core dumped). 
Here is my environment:
sys.platform:Linux;
Python: 3.8
CUDA available:True;

Here is the details:
train sample_idx: 007471
train sample_idx: 007472
train sample_idx: 007474
train sample_idx: 007476
train sample_idx: 007479
Traceback (most recent call last):
  File "/data1/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data6/yzy/ST3D/pcdet/datasets/kitti/kitti_dataset.py", line 470, in <module>
    create_kitti_infos(
  File "/data6/yzy/ST3D/pcdet/datasets/kitti/kitti_dataset.py", line 434, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/data6/yzy/ST3D/pcdet/datasets/kitti/kitti_dataset.py", line 191, in get_infos
    return list(infos)
  File "/data1/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/data1/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/data1/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/data1/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data6/yzy/ST3D/pcdet/datasets/kitti/kitti_dataset.py", line 128, in process_single_scene
    image_info = {'image_idx': sample_idx, 'image_shape': self.get_image_shape(sample_idx)}
  File "/data6/yzy/ST3D/pcdet/datasets/kitti/kitti_dataset.py", line 69, in get_image_shape
    assert img_file.exists()
AssertionError
Segmentation fault (core dumped)

**Comment by zhuoxiao-chen** [comment]
From "assert img_file.exists()", it looks like you miss some image files. Have you checked the completeness of your downloaded datasets?
